### ISSUE TITLE
Reduce the need to write to metadata server

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#135]
We currently write to metadata server for each block we upload to 0-stor server.
It is something unavoidable (at least for now) if that block is not part of bigger entity (i.e. the block is part of bigger block).

We might be able to write only one metadata for multiple blocks that is part of bigger entity (e.g. big file chunked into multiple chunks).
However, it will conflict with #126

**Comment by iwanbk** [comment]
The first step we can do (~if we really need to do it~) is to make the meta pipeline explicit again or at least the config module added it automatically if it doesn't see any components which write to metadata.

So, the distribution & stor.client component doesn't write to the metadata server.

**Comment by zaibon** [comment]
I have another propostion, cause I don't see how the `meta pipeline` would solve anything.

We need to change the capnp schema of the metadata. 
Currently it looks like this
```capnp
struct Metadata {
	size @0 :UInt64;
	# Size of the data in bytes

	epoch @1 :UInt64;
	# creation epoch

	key @2 :Data;
	# Key used in 0-stor

	encrKey @3 :Data;
	# Encryption key used to encrypt this file

	shard @4 :List(Text);
	# List of shard of the file. It's a url the 0-stor

	previous @5 :Data;
	# Key to the previous metadata entry

	next @6 :Data;
	# Key to the next metadata entry

	configPtr @7 :Data;
	# Key to the configuration used by the lib to set the data.

	numOfChunks @8:UInt64;
	# number of chunks
}
```

I propose to change it to 
```capnp
struct Metadata {
	size @0 :UInt64;
	# Size of the data in bytes

	epoch @1 :UInt64;
	# creation epoch

	key @2 :Data;
	# Key used in 0-stor

	encrKey @3 :Data;
	# Encryption key used to encrypt this file

	struct Chunk {
		key @0 :Data;
		# Key used in 0-stor

		size @1 :UInt64;
		# Size of the chunk in bytes

		Shards @2 :List(Text);
		# List of shards of the chunk. It's a url the 0-stor
	}
	chunks @4 :List(Chunk);
	# List of chunks of the file.
	# Can be only 1 if we don't split the file with chunker pipe

	previous @5 :Data;
	# Key to the previous metadata entry

	next @6 :Data;
	# Key to the next metadata entry

	configPtr @7 :Data;
	# Key to the configuration used by the lib to set the data.
}
```

With this schema, we can have a single metadata entry per file uploaded to the 0-stor. Even if the file is splitted into multiple chunks and each chunks erasure coded.

Also, since capnp doesn't allow to have resizable list, I think we should have a metadata struct which is passed along the pipeline instead of using the capnp msg. This allow to have easier code and I don't think it would consume more memory.
Then at the end of the pipeline, we create the capnp msg from the meta object and write only once to etcd.
This will also reduce greatly the load on the etcd, which already show some sign of overloading when cutting file in small chunks.

**Comment by iwanbk** [comment]
Loooks good except one thing that i'm not sure, will we have max number of chunks? Considering that we have embedded array there.

> Also, since capnp doesn't allow to have resizable list, I think we should have a metadata struct which is passed along the pipeline instead of using the capnp msg. This allow to have easier code and I don't think it would consume more memory.

Agree
