### ISSUE TITLE
0-stor: Create Go client

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#16]
Using the low level client library, create a Go client

**Comment by despiegk** [comment]
2 options

1. use https://github.com/zero-os/0-stor-lib
2. implement same specs using golang native, put also in repo mentioned in 1

**Comment by zaibon** [comment]
I would like 0-stor-lib to be done in golang directly so we can reuse it here to create the client

**Comment by despiegk** [comment]
where are the specs?

we once talked about giving the client the option to become a daemon with a e.g. grpc interface so that e.g. python can instruct the daemon to send/receive files. Is this still planned, can be a later release ofcourse.

at least we need a command line, where is that interface specked?

**Comment by iwanbk** [comment]
There is no spec right now.

Current client is only a Go package which can be used directly by other application like the tlog server.

Daemon is still planned.

We have some very simple cli in https://github.com/zero-os/0-stor/tree/master/client/cmd/cli
