### ISSUE TITLE
Rename main packages to something more meaningful 

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#169]
Currently the  package name and binaries produces by this repository are too generic (server, client, cli)

For the binary I propose we had a makefile that build into a bin directory with proper name. `zerostorserver` and `zerostorcli` to be consistent with the naming of the 0disk project.

And for the client package, we should also rename it to zerostorclient or something. Don't really like this name either but I have no better idea for now

**Comment by GlenDC** [comment]
The name should still be defined by the directory as that's go idiomatic (please do not define the name using `-o <name>` during builds, as that would still make `go get` installs fail. Often you have a root `/cmd` package, with there all your binaries in their separate directories. Shared code would be in other root packages (or sub packages of those root packages), while code-specific code would be in the binaries (sub)package.

e.g. https://github.com/kubernetes/kubernetes/tree/master/cmd

So for 0-stor that would mean something like

+ `github.com/zero-os/0-stor/cmd/zerostorctl`
+ `github.com/zero-os/0-stor/cmd/zerostorserver`

Calling the client package client is fine, you could also call it api, but either way both names or generic. This is really ok. Your name is already made unique by the packages in front of it (e.g. `github.com/zero-os/0-stor/client` or `github.com/zero-os/0-stor/api`).

It's rare that when using such client/api files that you have package conflicts, and for those case where you do Golang allows you to define a custom name for it as part of your import, so that in such cases people can still name it `zerostoclient` or `zerostorapi` (while importing) if they want.

**Comment by zaibon** [comment]
Yep make sense.
We already have a cmd package in the client. I'll just move it at the root and create another package for the server binary.
