### ISSUE TITLE
Remove requirement of valid IYO token for server testing

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#182]
If possible
original discussion https://github.com/zero-os/0-Disk/pull/400#discussion_r134648467

**Comment by iwanbk** [comment]
I myself think that it is fine to require valid IYO token.
@zaibon  @Hamdy  what do you think guys? You know the server better than me

**Comment by GlenDC** [comment]
It is absolutely not fine to require a valid IYO token for testing purposes of a local _TEST_ server... Now I require a IYO token for testing 0-Disk, why, why, why?

**Comment by zaibon** [comment]
The place where it's fine to require a jwt is the test for the rest and grpc handlers. All the lower layers have no knowledge of that. 

And indeed we should not push this requirement to the all test suite of 0-disk it makes life of everyone harder. 

I had a scheme where I could disable the jet check based on a environment variable. So during test I was settging this variable. Would that solution would be OK?

**Comment by GlenDC** [comment]
I'm not sure if even 0-stor should require such a test. On a unit-test level this should be tested only in IYO, wherever the client library for that thing lives. I suppose you could have it also as a requirement for some end-to-end testing in the 0-Stor codebase, but I'm not sure if that should really be a thing.

Having to set an environment variable could be a solution, but I would rather prefer if that could just be done purely via code. Especially in Go it's not uncommon to test directly using `go test`, rather than `Makefiles`, so requiring some random environment variables would really make that workflow a lot more painful than it should be.

**Comment by zaibon** [comment]
I would also prefer to do it directly in the code. But currently I don't know how I can disable the JWT validation. How would you do it ? a parameter somewhere ?

**Comment by zaibon** [comment]
I have another idea that would remove the need of credentials and allow the test to be performed off line.

What we could do is mock a IYO client which allow us to locally create jwt with proper scopes for our test. Then we would have to change the public key used for jwt validation from the IYO key to the public key of the key pair used by our mock client.

IYO package already define an interface for it's API 
```go
type NamespaceManager interface {
	CreateNamespace(namespace string) error
	DeleteNamespace(namespace string) error
	CreateJWT(namespace string, perm Permission) (string, error)
	GivePermission(namespace, userID string, perm Permission) error
	RemovePermission(namespace, userID string, perm Permission) error
	GetPermission(namespace, userID string) (Permission, error)
}
```

This can be splitted into 2 smaller interfaces. We can extract the `CreateJWT(namespace string, perm Permission) (string, error)` into it's own interface and then implement a mock client that generate JWT locally. Then we need to update the `jwt` package to be able to set the public used to validate JWT and we should be good to go.

**Comment by iwanbk** [comment]
Sounds good
