### ISSUE TITLE
Use protobuf for metadata encoding

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#199]
**See next comment,a bug in the benchmark make the number here false**

I did some comparison between capnp and protobuf v3 to see if it really make sense to use capnp as encoding system for the metadata. 
It appears that protobuf is more efficient in space even if we use capnp in packed mode.
Regarding the speed of encoding, capnp is better if we don't packed. But once we use the packed encoding, protobuf is faster

Code for the tests : https://github.com/zero-os/0-stor/blob/af3da5ce2a386cceda2f6ed1ae7a80fdd6a4e0ef/client/meta/meta_test.go

Here are the numbers:
```
size capnp: 10360
size capnp-packed: 9537
size protobuf: 8382
```

encoding speed:
```
BenchmarkEncoding/capnp-4                 200000             12133 ns/op
BenchmarkEncoding/capnp-packed-4           50000             26413 ns/op
BenchmarkEncoding/protobuf-4              100000             16176 ns/op
```

Regarding these numbers I propose to switch from capnp to protobuf for the metadata. 
The code generated by protobuf is much cleaner then capnp. Also we use grpc which already leverage protobuf. So we remove a completely  dependency by removing capnp

**Comment by zaibon** [comment]
**Update** 

I found a bug in my benchmark, I was not reseting the buffer used in the loop of the benchmark, which make the benchmark spent most of its time in growing the buffer and allocating memory. With the fix in the benchmark, capnp is way faster then anything else.

```
BenchmarkEncoding/capnp-4                3000000               482 ns/op
BenchmarkEncoding/capnp-packed-4           50000             25977 ns/op
BenchmarkEncoding/protobuf-4              100000             16328 ns/op
BenchmarkEncoding/msgpack-4               100000             20176 ns/op
```

**Comment by GlenDC** [comment]
So I guess we'll stick with non-packed capnp? As I'm fairly sure speed is much more a concern than space, or am I wrong?

**Comment by zaibon** [comment]
I also think speed should be the first concern here. The difference in size is no so big  and we have storage really cheap.

**Comment by GlenDC** [comment]
In that case we can close this issue, no? Or is there still something to be done?

**Comment by GlenDC** [comment]
Since PR #395 we use https://github.com/gogo/protobuf instead of google's protobuf and also instead of capnp. I compared the size and benchmarks as referenced in this issue, and https://github.com/gogo/protobuf is both much faster and more compact, is what I conclude after comparing the results.

Information about my dev machine:

```
OSX El Capitan (v10.11.6)

MacBook Pro (Retina, 13-inch, Early 2015)
CPU 2,7 GHz Intel Core i5
RAM 8 GB 1867 MHz DDR3
GPU Intel Iris Graphics 6100 1536 MB
```

Information about my Golang environment:

```
go version go1.9.2 darwin/amd64
```

When running the benchmarks and tests, with capnp still active, I get the following results:

> https://github.com/zero-os/0-stor/blob/16a3ab5af833602149891e1879b3fba7e0e249e2/client/meta/meta_test.go#L52-L80

> https://github.com/zero-os/0-stor/blob/16a3ab5af833602149891e1879b3fba7e0e249e2/client/meta/meta_test.go#L11-L29

```
BenchmarkEncoding/capnp-4         	    2000	    795802 ns/op	  666371 B/op	      23 allocs/op
BenchmarkEncoding/capnp-packed-4  	    2000	   1391883 ns/op	 1172181 B/op	      47 allocs/op

=== RUN   TestMetaSize/capnp
size capnp: 112744
=== RUN   TestMetaSize/capnp-packed
size capnp-packed: 99382
```

Now, when using gogo/protobuf, I get the following results:

> https://github.com/zero-os/0-stor/blob/9d4d1e42745427de528ec12a0607276e7b68ba1c/client/meta/encoding/proto/proto_test.go#L84-L94

> https://github.com/zero-os/0-stor/blob/9d4d1e42745427de528ec12a0607276e7b68ba1c/client/meta/encoding/proto/proto_test.go#L67-L82

```
BenchmarkMarshalMetadata-4   	   30000	     50727 ns/op	   63488 B/op	       2 allocs/op

--- PASS: TestMetaSize (0.00s)
	proto_test.go:76: size proto: 45701
```

And on top of being faster and more compact, we also allocate less while encoding.

On my machine gogoprotobuf seems be roughly 16 times faster compared to capnp,
and it seems to be roughly 27 times faster compared to capnp-packed.

Further it seems that for the same input metadata,
gogoprotobuf's output is 40% that of capnp's output
and 45% that of capnp-packed's output,
in terms of byte count.

Positing it here for historical reference.
