### ISSUE TITLE
server : possible race issue in the way we update object/reflist

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#264]
I see flaw in the way we update object.

Our current way:
- get object
- decode
- update
- encode

Imagine two client add ref list of same object and do the first step in the same time.
Then we will only have ref list added to the object.

As a comparison to other KV store like mongodb.
In mongodb,  we have `append` method which could work on field level. It guarantee the atomicity of the append operation.

**Comment by zaibon** [comment]
This is true. Lucky for us, badger is currently implementing transactions and MMVC, that should allow us to make these call atomic

**Comment by iwanbk** [comment]
>  Lucky for us, badger is currently implementing transactions and MMVC, that should allow us to make these call atomic

This?
> Transactions | No (but provides compare and set operations)

Interesting

**Comment by zaibon** [comment]
Now they only have CAS, but https://github.com/dgraph-io/badger/issues/230 real transaction in on the way.

**Comment by manishrjain** [comment]
Badger transaction support is in master: https://blog.dgraph.io/post/badger-txn/

**Comment by zaibon** [comment]
Although badger now has transaction supports. I think the design of the server does't really allow us to take advantage of it.
Currently the server logic works like this: 
There is the `db.DB` interface
https://github.com/zero-os/0-stor/blob/b1019f757683ee58ec9fb8b646476c49dd81caca/server/db/db.go#L4-L12

This interface is implemented by badger in [badger.go](https://github.com/zero-os/0-stor/blob/master/server/db/badger/badger.go)

Then we have the definition of the object in the db package
- https://github.com/zero-os/0-stor/blob/master/server/db/namespace.go
- https://github.com/zero-os/0-stor/blob/master/server/db/object.go
- https://github.com/zero-os/0-stor/blob/master/server/db/store_stat.go

At the beginning these only contains the struct definition and 2 methods, `Encode` and `Decode` to so we could serialize the object into binary. But due to https://github.com/zero-os/0-stor/issues/263 the object.go file became more complex and quite some logic has been moved into this file.

Then on top of the `db` package we have the `manager` package where all the business logic of how to store and retrieve data for is supposed to be. It has been created cause when we started this project 2 interface( REST and grpc) were supported, so we wanted a single point where we implement this logic and can be re-used by both interface. Now we dropped REST, so this is not really a requirement anymore.
Then last layer is the grpc handler where the method of the manager are called:
- https://github.com/zero-os/0-stor/blob/master/server/object_api.go
- https://github.com/zero-os/0-stor/blob/master/server/namespace_api.go
- https://github.com/zero-os/0-stor/blob/master/server/store_stat_api.go

Has you can see, the transaction feature from badger is only used really down in the flow and doesn't provide atomic operation at the grpc handler level. So I think we sill have the race condition present.

I don't see a way to fix this with the current organization of the code and we might want to rethink how it's done. Maybe the manager package doesn't have any reason to be anymore and we should just call badger method directly from the grpc handlers

**Comment by zaibon** [comment]
What I propose is that we try to validate that we still have a race condition, and from there decide what to do to fix it.

**Comment by iwanbk** [comment]
> What I propose is that we try to validate that we still have a race condition

Not sure i understand this statement, because you already validated that it is indeed an issue. And didn't show any fix attempt.

> What I propose is that we try to validate that we still have a race condition

On the other side, the server already designed as **simple** server while the complexity should be done in client side.
I was thinking that the concurrency should also be handled by the client, dunno

**Comment by GlenDC** [comment]
> I was thinking that the concurrency should also be handled by the client, dunno

It's still up to the server to ensure that any client action is applied without any possibility of a race condition. There is no way to do this even in the client-side, as multiple clients wouldn't/shouldn't communicate with one another about this.

**Comment by GlenDC** [comment]
This issue is resolved by the new 0-stor server design. It will be resolved in master once #324 is implemented (the new db interface and its implementations). A unit test will also have to be added to ensure that indeed such race conditions are no longer possible.
