### ISSUE TITLE
client : jwt refresh mechanism

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#314]
Client currently doesn't have JWT refresh mechanism.
How to handle JWT expiration?

**Comment by zaibon** [comment]
I though it was already in, but if not we need to add a way to refresh JWT if they are refreshable. And it needs to be transparent for the user.

**Comment by iwanbk** [comment]
> I though it was already in

Nope, as far as i can see.

>  but if not we need to add a way to refresh JWT if they are refreshable

Or simply create another JWT?

> And it needs to be transparent for the user.

How the strategy used by AYS/orchestrator?

**Comment by zaibon** [comment]
> Or simply create another JWT?
If we can refresh we should do it. If not we can create new jwt. 

> How the strategy used by AYS/orchestrator?
Orchestrator has a jwt provider object from which we always get the jwt. It ensure that if the jwt is expired it get refreshed before being returned to the user

**Comment by iwanbk** [comment]
> If we can refresh we should do it. If not we can create new jwt.

Yeah, that is what in my mind too.
Although i doubt it because the expiration time is encoded in the token.

**Comment by zaibon** [comment]
The expiration time is part of the claim of the token. The key is `exp`

**Comment by GlenDC** [comment]
Keeping them in cache is simple enough, and we can definitely make use of the expiration date. Although I would suggest to not use them until the last second, as that might make a jwt-token invalid by the time it reaches the server. 

Currently it seems that a token, generated and received from itsyou.online is valid for **24 hours**, so I think we can safely accept them until the last 5 minutes or so, and create a new one if it comes after that.

But, not sure if a cache in memory is that useful, as for many use cases the client code lives very short-lived (certainly is the case for when being used, using the zstor command-line tool). So perhaps we can also provide an option to provide another kind of cache, using the local FS, which is something we could use for the zstor command-line tool.

I'm just a bit concerned about how we currently use an unsecure connection, to transport the token between the zstor client and the zstordb server. Because a JWT token as it is, is not encrypted, just signed. So while it does proof ownership, it does also mean that anyone sniffing on our connection, can also use that token to claim ownership. And as these tokens seem to be available for 24 hours, it basically means that this potential attacker can do a lot of damage, as this is the only authentication we provide.

> But I'm a bit digressing here, so perhaps I should put this as a separate issue, but we should really provide the option to have a secure connection between server and client, as this is pretty bad.

CC @zaibon @iwanbk

**Comment by zaibon** [comment]
The creation of the JWT on itsyou.online can accept a `validity` argument to specify how long we want the JWT to be valid. If needed we can rejet token that have validity duration too long. So we ensure to keep a revocation delay relatively short.

> using the local FS, which is something we could use for the zstor command-line tool.

Indeed, goo idea.

> I'm just a bit concerned about how we currently use an unsecure connection

We indeed need to support TLS for grpc connection. Let's track progress of this on https://github.com/zero-os/0-stor/issues/333

**Comment by GlenDC** [comment]
> We indeed need to support TLS for grpc connection. Let's track progress of this on #333

Yeah I suppose we should never enforce it, but we can at least spit out warnings when an insecure connection is used.

And as we use an https connection for the IYO Web API, we should already be fine on that side of the story, so yeah, having a secure connection between the zstordb server and client should already help a bit.

The only thing I'm still concerned about is if we should cache to the local FS, we might need to encrypt it somehow if possible, because storing it unencrypted seems not like the best idea in the world.

**Comment by GlenDC** [comment]
I'm dropping the local FS persistent JWT Token cache for now as it adds a lot of complexity while optimizing something that doesn't give us that much benefits for now, as I don't think the command-line tool is meant for any serious usage, where you want to do more than a couple of operations.

And as I'm planning to limit the expiration TTL to 5 minutes (see my feature request in https://github.com/itsyouonline/identityserver/issues/684), there is also no point in a persistent cache for code-clients, as the tokens will expire pretty fast anyhow.

If it turns out that we do want to provide such a cache option, we can add such a feature request in a later phase.

**Comment by GlenDC** [comment]
I pretty much finished the work for this issue. You can find the code for my solution here: https://github.com/zero-os/0-stor/compare/master...GlenDC:jwt-cache

The only thing I have left to do is add some unit tests for the JWT cache to ensure it works as expected.

It's nothing fancy, just an in-memory LRU cache, using a bucket-strategy as to help us mitigate some of the mutex-lock cost. Expiration time is checked when creating a JWTToken, as well as when getting a JWTToken from cache, as to ensure a JWTToken has a reasonable expiration time when returning it to the user. When a JWTToken is retrieved from cache and turns out to be expired (or about to be expired), we'll remove it from the cache manually and try to create a token using the internal JWTTokenGetter.

When creating a 0-stor client using a config, there is currently no option to make it not cached, I think this is OK. Should it be required we can always add a config (boolean) parameter in a future release which allows to disable the cache (and thus make it opt-out). But for now I don't see the need for it, and it's always easier/better to add a feature, rather than removing one (and thus breaking people's code). So until there's the need for it, I'll just keep enforced for now, with no option to disable the in-memory JWT cache for the config-created 0-stor creation.
