### ISSUE TITLE
server : crash on delete

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#347]
got it once during client proxy development

https://github.com/zero-os/0-stor/blob/65060292f43a0c20a356f8c8b1e8004a14ba859f/server/db/object.go#L268-L274

```syslog
INFO[2017-11-23T14:24:21+07:00] Space reserved : 0B                          
INFO[2017-11-23T14:24:21+07:00] Space available : 3.881GiB                   
INFO[2017-11-23T14:24:21+07:00] Server interface: grpc                       
INFO[2017-11-23T14:24:21+07:00] Server listening on [::]:12346               
2017/11/23 17:25:11 Assert failed
github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/y.AssertTrue
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/y/error.go:55
github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*oracle).decrRef
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/transaction.go:74
github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*Txn).Discard
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/transaction.go:350
github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*Txn).Commit
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/transaction.go:411
github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*DB).Update
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/transaction.go:476
github.com/zero-os/0-stor/server/db/badger.BadgerDB.Delete
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/server/db/badger/badger.go:61
github.com/zero-os/0-stor/server/db/badger.(*BadgerDB).Delete
        <autogenerated>:2
github.com/zero-os/0-stor/server/db.(*Object).Delete
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/server/db/object.go:270
github.com/zero-os/0-stor/server/manager.(*ObjectManager).Delete
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/server/manager/object.go:62
github.com/zero-os/0-stor/server.(*ObjectAPI).Delete
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/server/object_api.go:144
github.com/zero-os/0-stor/grpc_store._ObjectManager_Delete_Handler
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/grpc_store/store.pb.go:803
github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).processUnaryRPC
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:781
github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).handleStream
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:981
github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:551
runtime.goexit
        /home/ibk/go/src/runtime/asm_amd64.s:2197
```

**Comment by GlenDC** [comment]
From a first quick inspection, it looks like it is a conflict with how we do the GC of Badger in our DB implementation (and how that GC cleaning leaves the internal badger state) and what some other internal badger function expects in state when it decrements the reference of an object we delete.

You can see how we currently clean-up/collect the garbage (runs every 10 minutes):

https://github.com/zero-os/0-stor/blob/65060292f43a0c20a356f8c8b1e8004a14ba859f/server/db/badger/badger.go#L209-L216

And here is the internal code where the panic is triggered from:

https://github.com/zero-os/0-stor/blob/65060292f43a0c20a356f8c8b1e8004a14ba859f/vendor/github.com/dgraph-io/badger/transaction.go#L70-L81

> The assert that makes the code fail is `y.AssertTrue(len(o.commitMark) == 0) `

>> https://github.com/zero-os/0-stor/blob/65060292f43a0c20a356f8c8b1e8004a14ba859f/vendor/github.com/dgraph-io/badger/transaction.go#L469-L483

>> This triggers the assert indirectly via `defer txn.Discard()`

The badger code from above is triggered by our UpdateTransaction->Delete code:

https://github.com/zero-os/0-stor/blob/65060292f43a0c20a356f8c8b1e8004a14ba859f/server/db/badger/badger.go#L77-L86

I don't yet know exactly why it fails. But at least this should give us a clue. There are two options here:

+ (1) There is a bug in BadgerDB code;
+ (2) The way we collect GC is wrong (in a subtle way);

Given that the BadgerDB code is not yet that mature, we can't rule out a bug in its code (1). However for now I would still like to think more that we're simply collecting the GC wrongly (2), as that is still the more likely option in my mind, if only because of history.

**Comment by GlenDC** [comment]
@iwanbk I chatted with the badger engineers over slack, and they're investigating the issue as we speak. It might be an issue on their side according to them. So far it doesn't seem like we're doing something too weird or I guess they would have noticed right away (I think).

Either way, for now this issue is frozen I guess, until we hear back from them.

They asked me to create an issue for it in badger, you can check it out here: https://github.com/dgraph-io/badger/issues/327

**Comment by GlenDC** [comment]
Turned out to be an actual bug in badger as predicted. And this has now been fixed in badger. That fix has also been merged into the master branch of master. So as soon as we update our vendored badger dependency, this issue is fixed.
