### ISSUE TITLE
Allow a namespace to be read only accessible by anyone

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#352]
For the use case of the 0-hub. We'll need the possibility to let anyone read the data from a namespace, even if the client is not authenticated. (see https://github.com/zero-os/home/blob/master/milestones/1.1.0-beta-2.md)

This is needed cause the 0-hub will use  0-stor as backend, and the data need to be readable publicly. So no authentification at all when trying to read.

Not sure yet how we should do this. I see multiple options:
- Add an API to the client to let him configure a namespace as publicly read-only. Then will have to store that information in badger somehow so it's persistent.
- Add a section in the configuration to let the administrator define namespace that is publicly read-only.

**Comment by GlenDC** [comment]
Let's discuss this in a zoom one of these days, before we decide anything.

**Comment by GlenDC** [comment]
@zaibon I think the most natural place for this would actually be in IYO. That's the place that handles all permissions already, and if we start to add a second layer (public read-only) which would disable this first layer (IYO), we potentially open a security back-door.

If somehow we can mark an organization as also being read-only for public, or perhaps we could even allow also read/write/delete on a public level (similar to what the Unix file system allows and stuff like Google Drive). That would keep it all under IYO. But than again, not even sure how that would work though, would you still work via tokens? Perhaps. Dunno.

We certainly can't add this information to the metadata, as that is not secure at all. We have zero-control over the metadata storage. There is nothing there we can guarantee for the user. Storing it along the data itself is weird and not convenient at all, so that's not an option either.

Hence the only, and not just natural, place I see for this feature is in IYO.

But how this would work/be-implemented, I have no clue at the moment.

What you think, @zaibon?

**Comment by GlenDC** [comment]
I'm also moving this to beta-3, as I really am sceptical that 0-hub will switch over to 0-stor, within less than a week time, even we somehow manage to implement this feature in the next few days in 0-stor (which we won't).

So doing this somewhere in the first week(s) of the next milestone seems more realistic. Gives us also time to work out and agree on the details (and direction) of this feature.

**Comment by GlenDC** [comment]
I like the idea of using the namespace for this, stored in zstordb, that does sound like a solution that could work. Doesn't have to require any user-action, except an extra permissions object that would indicate the Read/Write/Delete permissions for public use cases.

upon receiving an authentication request, the auth_jwt_middleware would first check in badger if for that specific permission the namespace is set to public, if so, it can simply pass already without having to validate the JWT token.

Or it can first try to validate the JWT token, and only if that fails, check badger, perhaps that's faster.

Either way, I don't think it requires any user-action, no static work, nothing up front. It would just require:

+ that we revive the namespace object concept (as for now we were no longer storing a namespace object);
+ that we create the namespace object when a namespace gets created from the command-line tool;
+ that we check this namespace object when verifiying the JWT token;

The only thing that's not clear to me is what if that namespace object doesn't exist? As the user might have created the namespace directly on itsyou.online, in which case there is no namespace object in zstordb...

All in all, the most natural place is therefore still itsyou.online :P perhaps we need a feature reuqest there.

**Comment by GlenDC** [comment]
I like the idea of using the namespace for this, stored in zstordb, that does sound like a solution that could work. Doesn't have to require any user-action, except an extra permissions object that would indicate the Read/Write/Delete permissions for public use cases.

upon receiving an authentication request, the auth_jwt_middleware would first check in badger if for that specific permission the namespace is set to public, if so, it can simply pass already without having to validate the JWT token.

Or it can first try to validate the JWT token, and only if that fails, check badger, perhaps that's faster.

Either way, I don't think it requires any user-action, no static work, nothing up front. It would just require:

+ that we revive the namespace object concept (as for now we were no longer storing a namespace object);
+ that we create the namespace object when a namespace gets created from the command-line tool;
+ that we check this namespace object when verifiying the JWT token;

The only thing that's not clear to me is what if that namespace object doesn't exist? As the user might have created the namespace directly on itsyou.online, in which case there is no namespace object in zstordb...

All in all, the most natural place is therefore still itsyou.online :P perhaps we need a feature reuqest there.

**Comment by zaibon** [comment]
> that we revive the namespace object concept (as for now we were no longer storing a namespace object);

That souldn't be. We should still gather statistics per namespace. Request/hour ect...

> that we create the namespace object when a namespace gets created from the command-line tool;

That can be added, but not really necessary. See next point

> The only thing that's not clear to me is what if that namespace object doesn't exist?

What we used to do, it to create the namespace automatically when receiving request with a valid JWT for this namespace. Cause indeed, user could have created it only on IYO, which is valid.

**Comment by GlenDC** [comment]
> That souldn't be. We should still gather statistics per namespace. Request/hour ect...

Those are never stored though. And unless I fucked something seriously up, I don't think they ever were.

> What we used to do, it to create the namespace automatically when receiving request with a valid JWT for this namespace. Cause indeed, user could have created it only on IYO, which is valid.

I mean while it in a way makes sense to allow this as part of a CreateObject request, iff the user is admin, it does look very weird to have a property as part of each createObject request which in facts impacts the entire namespace....

**Comment by zaibon** [comment]
>that we revive the namespace object concept (as for now we were no longer storing a namespace object);
That souldn't be. We should still gather statistics per namespace. Request/hour ect...

My bad, the stats were indeed never save onto disk. But the namespace object was saved back in alpha-8

**Comment by GlenDC** [comment]
> My bad, the stats were indeed never save onto disk. But the namespace object was saved back in alpha-8

Yes, but after the reservation stuff was removed again, that became useless.

**Comment by GlenDC** [comment]
We'll need a service between 0-stor and IYO, which allows us to keep track of namespace permissions, both user-specific and public. How that service would look like is yet to be defined.

**Comment by zaibon** [comment]
> We'll need a service between 0-stor and IYO, which allows us to keep track of namespace permissions, both user-specific and public. How that service would look like is yet to be defined.

This is for the futur. But for this release we still need a way to make a namespace publicly accessible for read-only. This is required for the 0-hub.

For this release, let's revive the namespace objects and add a command on `zstor namespace` to mark it read-only.
The command will ensure that the namespace exists on all the data shards referenced in the config, mark the namespace as read-only for public.
From the ztsordb perspective, we'll have to keep track of all the namespace that should be read-only in memory. The JWT intercerptor then check each read requests, and if the request if for a read-only namespace, it let the request pass without authentification.

**Comment by GlenDC** [comment]
That's a horrible idea, even for a temporary one.

As you want code to work with unlisted shards, as well as listed, there is no guarantee that all shards at all points in time will actually be properly marked as public, if they need to be so.

That being said, it would be a hack that would allow this feature for now. I suppose only admins would be able to execute that public read-only command?

**Comment by zaibon** [comment]
This is to enable our use case for the 0-stor. In this case we control all the shards of the 0-hub. So it's up to us to not fuckup the setup of the 0-stor cluster of the 0-hub. 

> it would be a hack that would allow this feature for now. I suppose only admins would be able to execute that public read-only command?

Yes only admin of the namespace can enable this.

**Comment by GlenDC** [comment]
I know, and for now this is probably the sanest approach (I suppose), will implement it today and open a PR. This way the milestone and hub doesn't get delayed, and this way I also stay free to work on stuff like the threefold project.

We just need to really make it clear in the code and documentation that this is a temporary and very hacky solution and will definitely change in the future.

**Comment by GlenDC** [comment]
Ok I have a WIP solution ready which does pretty much what you want.

The only issue is however that our namespace (labels) are different when IYO config is defined, compared to when it is not defined. This because we use the namespace format `<org>_0stor_<label>` when IYO is defined, otherwise we use `<label>`.

One solution could be to use the actual label as the label for zstordb non-auth purposes. However that would mean that a label has to be unique within a given organization, which is not something we can guarantee as easily.

However, without an IYO config it's impossible to generate a namespace in the `<org>_0stor_<label>` format, as we wouldn't know the organization.

So not sure what to do with this. Will think about it, but for now this issue is blocked on that, as all the rest of the code is ready.

**Comment by GlenDC** [comment]
I have an alternative solution, which would be even easier to use.

We already store data as objects in badger, using the following key format: `d:<namespace>:<key>`, where the `namespace` is in the format discussed earlier (`<org>_0stor_<label>`). This is great as it means we can easily list all object (should we want) by listing all values that are stored under `d:<namespace>`. This is important information to keep in mind, as we'll come back to this in a second.

Now we could on top of that also store a simple 32 bit integer (or even less, but I would make it big enough from the start), and 32 bit would allows us 32 flags which I think is good enough (but we could even go for 64 bit or higher), we can also go for an infinite bit-flag range, but than we need to be smart in how to serialize it. Either way this has no impact on the idea, so let's re-focus.

The important part is that we would store the metadata as a separate value under the key `md:<namespace>:<key>`. This has 2 advantages:

+ it means we don't have to break the data format ever, keeping it stable (forever, ever, ever...);
+ it mean we don't have to load the entire data each time we want to read or modify the flags (for now modification of flags isn't needed even);

It does have one disadvantage:

+ due to a data(base) corruption the metadata of an object might get lost (this would indicate perhaps a flaw in the database internally, but it is a possibility to take into account none the less), while the data isn't lost, meaning that when repairing the data or reading the data you might think it's not public-read-accessible, while really it is;

Than we would change the code such that when you create data (see uploading data), you also define whether or not it has to be public-read-accessible. On the lowest level that would mean that the CreateObject RPC function's request would change to:

```diff
diff --git a/server/api/grpc/schema/zstor.proto b/server/api/grpc/schema/zstor.proto
index 5e9815e..9d60e69 100644
--- a/server/api/grpc/schema/zstor.proto
+++ b/server/api/grpc/schema/zstor.proto
@@ -133,6 +133,7 @@ service ObjectManager {
 
 message CreateObjectRequest {
     bytes data = 1;
+    bool publicRead = 2;
 }
 message CreateObjectResponse {
     bytes key = 1;
```

It's as simple as a boolean that would be given by the user (at the highest level via a flag when  uploading the file, so easy peasy. When repairing data this isn't required, as we can simply use the read-only flag from the read data. In a way if you want to be really sure you could merge the flags into the actual data. That would prevent a scenario where the data object is not but the metadata object is missing (while it did exist). Corruption is not possible (see: rather unlikely) as all data is stored using a (CRC32) checksum.

This alternative solution has the following advantages over the original solution we came up with earlier, @zaibon:

+ It is not required to mark a namespace as public-read-only, so no need for the SetFlag, GetFlag functions. As a consequence this makes unlisted shards still supported, as long as the data was created using the correct flags, it will always work;
+ It becomes much simpler from a user perspective (avoiding those extra functions);
+ The public-read-accessible property becomes much more fine-grained (e.g. you can have some files in a namespace to be public read-only, while others you have not);
   + note: depending on your POV this might be a disadvantage as it means humans can forget they have some files as public-accessible within a namespace, when later they decide to make a bunch of files private again, while when doing this on a namespace level, this is less likely to happen;

It does still have some security-related issue(s). Note however that these same issue(s) are also applying to the originally proposed idea, for which I already have local code ready:

+ If a hacker can access the local FS, it can also modify these flags, and thus make data read-accessible;
   + note however that this is perhaps a non-issue, as public read-accessible data would anyhow be not encrypted (otherwise its public property is of little use), and thus that hacker can read that data anyhow, so this is really a security limitation that would have anyhow, even without this kind of newly added metadata;
+ this does really, really, really mean that we need to recommend and use in production TLS protected connections (anyhow that was already required, as we also share JWT tokens);

So yeah, I'll implement this solution as well. As I think it's better than the original implemented solution, and this issue is critical. So when you're back @zaibon, you can just merge in whichever of the two solutions you like most.

**Comment by despiegk** [comment]
we are going overboard here, the idea was NOT having to use IYO apart from maybe identification but for sure not storing of metadata to do with this service.


a very simple concept where each storage server can check on can this user access this namespace or not & is there enough capacity left in the reservation.

without this we cannot go life so thats kind of not very good.

lets discuss

**Comment by GlenDC** [comment]
These are just brainstorms, but yeah sure, if you have better ideas I'm all ears. Always.

**Comment by zaibon** [comment]
will be solved by https://github.com/zero-os/0-db/issues/7 and #515
