### ISSUE TITLE
Make some test with badger to know how much storage is really used on disk

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#488]
Relates to : #487 

We need to know how much disk space is used by badger when writing data to it.
So how much disk space is consumed when we write n bytes to badger.

We also need to know how long it takes to reclaim disk space once data is deleted.
All these information will allow us to know how much of a disk we can reserve.

**Comment by GlenDC** [comment]
> We need to know how much disk space is used by badger when writing data to it.
> So how much disk space is consumed when we write n bytes to badger.

I'm investigating this, this should be do-able.

> We also need to know how long it takes to reclaim disk space once data is deleted.

I don't think this is going to be possible, as badger GC is not deterministic. The only control you have is the discard ratio, which defines how big part of a log file is to be discarded in order to define whether or not that file has to be rewritten (and thus cleaned up), as data is stored in groups, where each group is a file.

Besides that it is random, in the sense that when we trigger the GC to start, it will only do so until it find random log files it can clean up. As soon as it encounters a log file that doesn't have to be discarded, it simply stops the GC process. At least that's what I seem to understand from it.

Therefore I'm not sure how we'll be able to know which data is actually deleted.

A very naive solution could be to take into account a big enough amount of waste, bigger than the amount of waste (as in files that should be deleted/rewritten) which is expected in the worst case. But this is not ideal as it would mean the hosters would be able to earn less due to not being able to maximize their disk usage.

**Comment by GlenDC** [comment]
Apparently badger keeps track internally a lot of useful information about the GC and storage (e.g. which log file a piece of data belongs to, which pieces-of-data/files can be discarded/deleted, ...). This is for now however private.

The maintainers of Badger are however open to expose that kind of information to the public API, which could help us in order to use this information as to help us build/implement our reservation system.

Need to investigate what exactly we want, what is possible and than I'll start making issues for it in the Badger issue so we can start working towards a badger version which will allow us to implement the reservation system we envision.

**Comment by zaibon** [comment]
closed in favor of #515
