### ISSUE TITLE
add klauspost/reedsolomon as distribution library

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-stor#69]
We already have templexxx/reedsolomon

**Comment by iwanbk** [comment]
> We already have templexxx/reedsolomon

Yeah, but the reason we chose this library because it is compatible with what C++ tlog server use.

Another reasons:
- templexxx/reedsolomon has no mature API yet, there was one API change during development of distribution. And it seems that there will be another API change, i hope not.
- we have not benchmarked templexxx and klauspost

**Comment by GlenDC** [comment]
@iwanbk perhaps you should first make an issue than, which aims to benchmark klauspost and compares it with equal benchmarks of templexxx. This would serve as motivation to use klauspost over templexxx.

**Comment by GlenDC** [comment]
`klauspost/reedsolomon` only claims 1GB/s/core, while templexxx claims 10GB/s/core, so I don't see why we would want to go for something slower.

On top of that, users of 0-stor can already implement their own [`DistributedEncoderDecoder`](https://godoc.org/github.com/zero-os/0-stor/client/pipeline/storage#DistributedEncoderDecoder) to be used as part of the [`DistributedChunkStorage`](https://godoc.org/github.com/zero-os/0-stor/client/pipeline/storage#DistributedChunkStorage), so if a user would want the `klauspost/reedsolomon` they could easily implement and use it.

Therefore I think we can close this issue, even though it was not even planned yet.
